name: Push NPM Packages Input Versions 

on:
  workflow_dispatch:
    inputs:
      Type:
        description: 'NPM Tag Type'
        required: true
        type: choice
        options:
          - Minor
          - Major

jobs:
   Status-Input-Tag:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.validate_tag.outputs.new_tag }}
      flag: ${{ steps.validate_tag.outputs.status_flag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: the-peoples-clearinghouse/github-shared-actions
          token: ${{ secrets.ORG_PAT }}
          path: shared-actions

      - name: Input Tag Version
        id: validate_tag
        uses: ./shared-actions/actions/Input-Tag
        with:
          Type: ${{ inputs.Type }}

  Push-New-Tag:
    runs-on: ubuntu-latest
    needs: Status-Input-Tag
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: the-peoples-clearinghouse/github-shared-actions
          token: ${{ secrets.ORG_PAT }}
          path: shared-actions

      - name: Push New Tag
        uses: ./shared-actions/actions/Npm-Push
        with:
            New_Tag: ${{ needs.Status-Input-Tag.outputs.npm_tag }}
            gcp_credentials: ${{ secrets.GCP_JSON_AUTH }}