name: Publish to Artifact Registry on PR Close

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:

  Type-pull-request:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'fix:')
    steps:
      - name: Checks if is a Patch Version
        run: echo "New Patch Version Aproved"

  Update-Tag:
    runs-on: ubuntu-latest
    needs: Type-pull-request
    outputs:
      npm_tag: ${{ steps.get_new_patch.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: the-peoples-clearinghouse/github-shared-actions
          token: ${{ secrets.ORG_PAT }}
          path: shared-actions

      - name: Generate New Patch
        id: get_new_patch
        uses: ./shared-actions/actions/Patch-Tag

  Push-New-Tag:
    runs-on: ubuntu-latest
    needs: Update-Tag
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: the-peoples-clearinghouse/github-shared-actions
          token: ${{ secrets.ORG_PAT }}
          path: shared-actions

      - name: Push New Tag
        uses: ./shared-actions/actions/Npm-Push
        with:
            New_Tag: ${{ needs.Update-Tag.outputs.npm_tag }}
            gcp_credentials: ${{ secrets.GCP_JSON_AUTH }}
            Git_Token: ${{ secrets.ORG_PAT }}